-- bookManger_v5/book.sql

DROP TABLE BOOK CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_BID;

CREATE TABLE BOOK (
    BOOK_ID NUMBER,
    TITLE VARCHAR2(50) CONSTRAINT NIN_TITLE NOT NULL,
    AUTHOR VARCHAR2(20) CONSTRAINT NIN_AUTHOR NOT NULL,
    PUBLISHER VARCHAR2(20) CONSTRAINT NIN_PUBLISHER NOT NULL,
    PUBLISH_DATE DATE CONSTRAINT NIN_PUBLISHDATE NOT NULL,
    PRICE NUMBER CONSTRAINT NIN_PRICE NOT NULL,
    CONSTRAINT PK_BID PRIMARY KEY (BOOK_ID)
);

COMMENT ON COLUMN BOOK.BOOK_ID IS '도서번호';
COMMENT ON COLUMN BOOK.TITLE IS '도서명';
COMMENT ON COLUMN BOOK.AUTHOR IS '저자명';
COMMENT ON COLUMN BOOK.PUBLISHER IS '출판사';
COMMENT ON COLUMN BOOK.PUBLISH_DATE IS '출판날짜';
COMMENT ON COLUMN BOOK.PRICE IS '가격';

CREATE SEQUENCE SEQ_BID
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE;

INSERT INTO BOOK VALUES (SEQ_BID.NEXTVAL, '자바자료구조', '홍길동', 
'한빛', TO_DATE('17/09/28','RR/MM/DD'), 25000);
INSERT INTO BOOK VALUES (SEQ_BID.NEXTVAL, '초보자를 위한 자바', '이순신', 
'정보문화사', TO_DATE('18/07/15','RR/MM/DD'), 25200);
INSERT INTO BOOK VALUES (SEQ_BID.NEXTVAL, '자바입문', '김유신', 
'더빛', TO_DATE('19/01/28','RR/MM/DD'), 22000);
INSERT INTO BOOK VALUES (SEQ_BID.NEXTVAL, '자바의 정석', '김삿갓', 
'더원', TO_DATE('15/05/25','RR/MM/DD'), 24000);
INSERT INTO BOOK VALUES (SEQ_BID.NEXTVAL, '자바 별거 없다', '호랑이', 
'담배', TO_DATE('12/02/22','RR/MM/DD'), 40000);

COMMIT;